image: docker:stable

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "lucas"
      when: always
cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/
    - .next/
    
stages:
  - npm-build
  - docker-build
  - deploy

variables:
  IMAGE: registry.gitlab.com/equipe-de-projetos/social-media-frontend:$CI_COMMIT_SHORT_SHA
  BASE_IMAGE: node:18-alpine
  RUNNER_TAG: social-media-frontend
  APPNAME: social-frontend
  
npm-build:
  stage: npm-build
  environment: $CI_COMMIT_BRANCH
  tags:
    - $RUNNER_TAG
  image: node:18-alpine
  script:
    - cp .env.default .env.local  
    - npm ci 
    - npm run build  

docker-build:
  stage: docker-build
  environment: $CI_COMMIT_BRANCH
  tags:
    - $RUNNER_TAG 
  image: docker:stable  
  services:
    - name: docker:dind
  script:  
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build . --build-arg BASE_IMAGE=$BASE_IMAGE -t $IMAGE
    - docker push $IMAGE
    

# deploy:   
#   stage: deploy
#   environment: $CI_COMMIT_BRANCH  
#   tags:
#     - $RUNNER_TAG  
#   image: docker:stable
#   cache: []
#   before_script:
#    # - apk add --no-cache docker-compose   # instala no Alpine (imagem docker:stable é baseada em Alpine)
#   script:                
#     # - docker run -d -p 3000:3000 --name $APPNAME $IMAGE
    
    