'use client';

import type { Metadata } from "next";
import {  Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "../../providers/providers";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
}); 

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // optional: add more weights if needed
});

// export const metadata: Metadata = {
//   title: "My social media",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <meta name="msapplication-TileColor" content={"#000"} />
        <meta name="theme-color" content={"#000"} />
        <meta httpEquiv="X-UA-Compatible" content="IE=10" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="description" content="Your videos. Your stream 🌎." />
        <meta name="author" content="SocialMedia" />
        <meta name="keywords" content="Social Media, Friends, Communities, Fun" />

        <meta name="google-site-verification" content="" />
        <link rel="icon" type="image/ico" href="/fav.ico"></link>
        <link rel="shortcut icon" type="image/ico" href="/favicon.ico"></link>
        <link
          rel="apple-touch-icon"
          type="image/ico"
          href="/favicon.ico"
        ></link>

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="SocialMedia" />
        <link rel="apple-touch-icon" href="/favicon.ico" sizes="180x180" />

        <link rel="manifest" href="/manifest.json" />

        <title>Social Media</title>
      </head>
      <body suppressHydrationWarning={true} className={poppins.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
